### ISSUE TITLE
Automate docker image deployment

### ISSUE THREAD

**Issue by LongLiveCHIEF** [HackerHappyHour/reveal#22]
Automate deployment to https://hub.docker.com/u/hackerhappyhour.

- [x] determine strategy on _when_ to push
- [x] determine strategy on tagging
- [x] implement automation for strategies
- [ ] document strategies in `CONTRIBUTING.md`

**Comment by LongLiveCHIEF** [comment]
This article from Circle Ci might be of use: https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/

**Comment by nickshine** [comment]
In #27 , I've implemented a strategy to only publish Docker images when a new version is detected from the semantic release tool, and only on `master`.
