### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by LongLiveCHIEF** [HackerHappyHour/reveal#3]
- [x] comment about this being a fork of hakimel/reveal.js (and why)
- [x] statement about accepting requests for maintainers/collaborators to join HHH and/or help maintain reveal.js
- [x] add a roadmap with planned features, changes, and plans to pull merge requests from hakimel/reveal.js
- [ ] update install instructions to use `npm` (and to use the new publish location `@h3/reveal.js`

Anything else that's relevant for the "fork" that I'm missing?

**Comment by LongLiveCHIEF** [comment]
@nickshine  Should we add a link to our discord server and the reveal channel?

**Comment by nickshine** [comment]
@LongLiveCHIEF absolutely!
