### ISSUE TITLE
Publish current to npm.js as @h3/reveal

### ISSUE THREAD

**Issue by LongLiveCHIEF** [HackerHappyHour/reveal#4]
So I'm wondering if we should tag this first publish as `1.0`, `4.0`, or `3.7`. Open to suggestions on what would be best with this fresh start and new location.

**Comment by nickshine** [comment]
I'm thinking `1.0`, if we're going to veer off the path a bit with this.  I imagine there will be a `3.8` in the upstream at some point, although the release before `3.7` on upstream was about a year prior, and a few minor releases per year before that 🤔 .

**Comment by LongLiveCHIEF** [comment]
done!
